version: '3.4'

services:
  learn-postgres-db:
    image: postgres:16.1
    ports:
      - "5433:5432"
    volumes:
      - learn_postgres_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  learn_postgres_db_data:
